GTX480:
    base_file: "$GPGPUSIM_ROOT/configs/GTX480/gpgpusim.config"
    extra_params: ""

GTX480-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/GTX480/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 10"

QUADROFX5600:
    base_file: "$GPGPUSIM_ROOT/configs/QuadroFX5600/gpgpusim.config"
    extra_params: ""

QUADROFX5600-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/QuadroFX5600/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 10"

QUADROFX5800:
    base_file: "$GPGPUSIM_ROOT/configs/QuadroFX5800/gpgpusim.config"
    extra_params: ""

QUADROFX5800-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/QuadroFX5800/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 10"

TESLAC2050:
    base_file: "$GPGPUSIM_ROOT/configs/TeslaC2050/gpgpusim.config"
    extra_params: ""

TESLAC2050-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/TeslaC2050/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 10"

GTX750Ti:
    base_file: "$GPGPUSIM_ROOT/configs/GeForceGTX750Ti/gpgpusim.config"
    extra_params: ""

GTX750Ti-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/GeForceGTX750Ti/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 10"

PASCALTITANX:
    base_file: "$GPGPUSIM_ROOT/configs/PascalTitanX/gpgpu-sim-3.x/gpgpusim.config"
    extra_params: ""

PASCALTITANX-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/PascalTitanX/gpgpu-sim-3.x/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 10"

P100-HBM:
    base_file: "$GPGPUSIM_ROOT/configs/Pascal-P102-GDDR5X/gpgpusim.config"
    extra_params: ""

TITANX-P102:
    base_file: "$GPGPUSIM_ROOT/configs/Pascal-P100-HBM/gpgpusim.config"
    extra_params: ""

P100-HBM-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/Pascal-P102-GDDR5X/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 10"

TITANX-P102-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/Pascal-P100-HBM/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 10"
