# Basefile Configs

# Pascal
TITANX:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM6_TITANX/gpgpusim.config"

TITANXX:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/TITANX-pascal/gpgpusim.config"

#Kepler
TITANK:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM3_KEPLER_TITAN/gpgpusim.config"


#Turing
RTX2060:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/Turing_RTX2060/gpgpusim.config"

# Volta
TITANV:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM7_TITANV/gpgpusim.config"

# Volta
TITANV_OLD:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM7_TITANV_OLD/gpgpusim.config"

QV100:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM7_QV100/gpgpusim.config"

QV100_64SM:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM7_QV100_SMs/gpgpusim.config"


QV100_SASS:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM7_QV100_SASS/gpgpusim.config"

QV100_old:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM7_QV100_old/gpgpusim.config"

# Fermi
GTX480:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM2_GTX480/gpgpusim.config"

############################################################################

# Extra configs - these are composable.
# The names here will be appended to the basefile name with hyphens
#   For example TITANX-L1ON-PTXPLUS

64SM:
    extra_params: "-gpgpu_n_clusters 64"

PTXPLUS:
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 10"

SM_2:
    extra_params: "-gpgpu_ptx_force_max_capability 20"

L1ON:
    extra_params: "-gmem_skip_L1D 0"

L1OFF:
    extra_params: "-gmem_skip_L1D 1"

COPYK:
    extra_params: "-perf_sim_memcpy 1"

NCOPYK:
    extra_params: "-perf_sim_memcpy 0"

5B:
    extra_params: "-gpgpu_max_insn 5000000000"

2B:
    extra_params: "-gpgpu_max_insn 2000000000"

1B:
    extra_params: "-gpgpu_max_insn 1000000000"

5B:
    extra_params: "-gpgpu_max_insn 5000000000"

100M:
    extra_params: "-gpgpu_max_insn 100000000"

FLUSHL1:
    extra_params: "-gpgpu_flush_l1_cache 1"

PWR_ENABLE:
    extra_params: "-power_simulation_enabled 1"

LOCALXBAR:
    extra_params: "-network_mode 2 -inct_in_buffer_limit 512  -inct_out_buffer_limit 512  -inct_subnets 2"

BOOKSIM:
    extra_params: "-network_mode 1 -inter_config_file config_volta_islip.icnt"

1455MHZ:
    extra_params: "-gpgpu_clock_domains 1455.0:1455.0:1455.0:850.0"

1132MHZ:
    extra_params: "-gpgpu_clock_domains 1132.0:1132.0:1132.0:850.0"

NORM:
    extra_params: "-memory_partition_indexing 0"

XOR:
    extra_params: "-memory_partition_indexing 1"

RANDOM:
    extra_params: "-memory_partition_indexing 4"

PAE:
    extra_params: "-memory_partition_indexing 3"

IPOLY:
    extra_params: "-memory_partition_indexing 2"

TRACE:
    extra_params: "-trace_driven_mode 1"

EXEC:
    extra_params: "-trace_driven_mode 0"

RR:
    extra_params: "-gpgpu_scheduler lrr"

128B:
    extra_params: "-gpgpu_mem_addr_mapping dramid@7;00000000.00000000.00000000.00000000.0000RRRR.RRRRRRRR.RBBBCCCC.BCCSSSSS"

256B:
    extra_params: "-gpgpu_mem_addr_mapping dramid@8;00000000.00000000.00000000.00000000.0000RRRR.RRRRRRRR.RBBBCCCB.CCCSSSSS"

FRFCFS:
    extra_params: "-gpgpu_dram_scheduler 1"

FCFS:
    extra_params: "-gpgpu_dram_scheduler 0"

# Experimental - for SM 60 PTXplus support
PTXPLUS_SM6:
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 62 -gpgpu_ptx_force_min_capability 60"

##############################################################################
##############################################################################
# Deprecated files in the public repo
QUADROFX5600:
    base_file: "$GPGPUSIM_ROOT/configs/4.x-cfgs/SM1_QFX5600/gpgpusim.config"

QUADROFX5800:
    base_file: "$GPGPUSIM_ROOT/configs/4.x-cfgs/SM1_QFX5800/gpgpusim.config"

TESLAC2050:
    base_file: "$GPGPUSIM_ROOT/configs/4.x-cfgs/SM2_C2050/gpgpusim.config"
