# This is a basic workflow to help you get started with Actions

name: Tracer Tool

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the mydev branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Tracer-Tool:
    if: github.repository == 'accel-sim/accel-sim-framework'
    runs-on: tgrogers-gpu01
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          rm -rf env-setup
          git clone git@github.com:purdue-aalp/env-setup.git 
          cd env-setup 
          git checkout cluster-ubuntu
      - name: Build Accel-Sim
        run: |
          source ./env-setup/11.7.0_env_setup.sh
          rm -rf ./gpu-simulator/gpgpu-sim
          source ./gpu-simulator/setup_environment.sh
          make clean -C gpu-simulator
          make -j -C gpu-simulator
      - name: test-prebuilt-traces
        run: |
          source ./env-setup/11.7.0_env_setup.sh
          source ./gpu-simulator/setup_environment.sh
          ./get-accel-sim-traces.py -a tesla-v100/rodinia_2.0-ft
          cd hw_run; tar -xzvf rodinia_2.0-ft.tgz; cd -
          ./util/job_launching/run_simulations.py -B rodinia_2.0-ft -C QV100-SASS -T ./hw_run/ -N rodinia_2.0-ft-online-$$
          ./util/job_launching/monitor_func_test.py -N rodinia_2.0-ft-online-$$ -v
          rm -rf hw_run
          rm -rf sim_run_11.7.0
      - name: Build Tracer
        run: |
          source ./env-setup/11.7.0_env_setup.sh
          ./util/tracer_nvbit/install_nvbit.sh
          make clean -C ./util/tracer_nvbit/
          make -C ./util/tracer_nvbit/
      - name: rodinia_2.0-ft-build
        run: |
          source ./env-setup/11.7.0_env_setup.sh
          rm -rf ./gpu-app-collection/
          git clone git@github.com:accel-sim/gpu-app-collection.git
          source ./gpu-app-collection/src/setup_environment
          ln -s /home/tgrogers-raid/a/common/data_dirs ./gpu-app-collection/
          make -C ./gpu-app-collection/src rodinia_2.0-ft
      - name: generate-rodinia_2.0-ft-traces
        run: |
          source ./env-setup/11.7.0_env_setup.sh
          source ./gpu-app-collection/src/setup_environment
          rm -rf ./hw_run/
          ./util/tracer_nvbit/run_hw_trace.py -B rodinia_2.0-ft -D 7
      - name: generate-rodinia_2.0-ft-hw_stats
        run: |
          source ./env-setup/11.7.0_env_setup.sh
          source ./gpu-app-collection/src/setup_environment
          ./util/hw_stats/run_hw.py -B rodinia_2.0-ft -D 7
      - name: test-new-traces
        run: |
          source ./env-setup/11.7.0_env_setup.sh
          source ./gpu-simulator/setup_environment.sh
          ./util/job_launching/run_simulations.py -B rodinia_2.0-ft -C QV100-SASS -T ./hw_run/traces/device-7/11.7/ -N rodinia_2.0-ft-$$
          ./util/job_launching/monitor_func_test.py -I -v -s rodinia-stats-per-app.csv -N rodinia_2.0-ft-$$